# Generated by Django 5.2.5 on 2025-08-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada da subtarefa', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Data e hora limite para conclusão da subtarefa', null=True, verbose_name='Data Limite'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='estimated_duration',
            field=models.DurationField(blank=True, help_text='Tempo estimado para conclusão da subtarefa', null=True, verbose_name='Duração Estimada'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionais sobre a subtarefa', verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', help_text='Nível de prioridade da subtarefa', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='reminder',
            field=models.DateTimeField(blank=True, help_text='Data e hora para lembrete da subtarefa', null=True, verbose_name='Lembrete'),
        ),
    ]
