# Generated by Django 5.2.5 on 2025-08-28 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria (máximo 50 caracteres)', max_length=50, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da categoria', verbose_name='Descrição')),
                ('color', models.CharField(default='#007bff', help_text='Cor da categoria em formato hexadecimal (ex: #007bff)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(help_text='Usuário proprietário da categoria', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
