# Generated by Django 5.2.5 on 2025-08-28 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da etiqueta (máximo 30 caracteres)', max_length=30, verbose_name='Nome')),
                ('color', models.CharField(default='#6c757d', help_text='Cor da etiqueta em formato hexadecimal (ex: #6c757d)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato hexadecimal (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(help_text='Usuário proprietário da etiqueta', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
