# Generated by Django 5.2.5 on 2025-08-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da lista (máximo 100 caracteres)', max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da lista', verbose_name='Descrição')),
                ('custom_profile', models.BooleanField(default=False, help_text='Indica se a lista possui configurações personalizadas', verbose_name='Perfil Personalizado')),
                ('auto_suggestion', models.BooleanField(default=False, help_text='Permite que o sistema sugira automaticamente tarefas para esta lista', verbose_name='Sugestão Automática')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(help_text='Usuário proprietário da lista', on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lista de Tarefas',
                'verbose_name_plural': 'Listas de Tarefas',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
